services:
  postgres_test:
    image: postgres:17
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_test
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  node_server_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_server_test_container
    command: npm run dev
    env_file:
      - .env.test
    ports:
      - '8000:8000'
    depends_on:
      postgres_test:
        condition: service_healthy
