services:
  postgres_test:
    image: postgres:17
    container_name: postgres_test_container
    env_file:
      - .env.test
    ports:
      - '5432:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  node_server_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_server_test_container
    env_file:
      - .env.test
    ports:
      - '8000:8000'
    depends_on:
      - postgres_test

volumes:
  postgres_test_data:
